exe-1.3: exe-1.3.o
	cc exe-1.3.c -o exe-1.3.o

exe-1.4: exe-1.4.o
	cc exe-1.4.c -o exe-1.4.o

exe-1.5: exe-1.5.o
	cc exe-1.5.c -o exe-1.5.o

exe-1.6: exe-1.6.o
	cc exe-1.6.c -o exe-1.6.o

exe-1.7: exe-1.7.o
	cc exe-1.7.c -o exe-1.7.o

exe-1.8: exe-1.8.o
	cc exe-1.8.c -o exe-1.8.o

exe-1.9: exe-1.9.o
	cc exe-1.9.c -o exe-1.9.o
